import type { Metadata } from 'next'
import { DashboardSiderbar } from './siderbar'

export const metadata: Metadata = {
  title: 'Dashboard - Simple Aplikasi Cuti',
  description: 'Generated by create next app',
}
export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="min-h-screen flex gap-x-2 bg-slate-300">
      <div>
        <DashboardSiderbar />
      </div>
      <div className="m-2 rounded w-screen bg-white">
        <div className="container mx-auto p-6">{children}</div>
      </div>
    </div>
  )
}
